### ISSUE TITLE
Abandoned_carts: What is move and move_line in querry mean?

### ISSUE THREAD

**Issue by DavidNitro** [Nitrokey/odoo-modules#12]
What does account_move & account_move_line in query at line 34 and 35 in customer.py mean?

**Comment by nikunjantala** [comment]
account_move & account_move_line is the table of odoo. In that customer/partner is set(many2one).

**Comment by DavidNitro** [comment]
thank you. Can you specify please? these both have to be null. Why? the other query's I understand but this one i can't explain. Maybe you can explain it by an example?

**Comment by DavidNitro** [comment]
Thank you very much for your explanation. Now I understand what you mean.
