### ISSUE TITLE
Abandoned_carts: Subscription is deactivated by deleting customer

### ISSUE THREAD

**Issue by DavidNitro** [Nitrokey/odoo-modules#13]
When subscribing for newsletter and deleting customer he/she is unsubscribed. Please check.

**Comment by nikunjantala** [comment]
I have fixed that issue. Now you can do testing. It will not unsubscribe  deleting customer/partner.

**Comment by DavidNitro** [comment]
It still doesn't work

**Comment by DavidNitro** [comment]
everything works fine. Thank you
