### ISSUE TITLE
vat_online_validation: can't change invalid VAT ID

### ISSUE THREAD

**Issue by jans23** [Nitrokey/odoo-modules#14]
With Odoo 12, when I order something as a customer (from a company) and type in a valid VAT number, it works fine. When I type in an invalid VAT number, then i get a red frame around the VAT and can't proceed. The problem here is, that i can't change the VAT number afterwards when i type in a false one.
![false VAT](https://user-images.githubusercontent.com/1450547/71371753-8260a680-25b2-11ea-8256-02e9a1a2e4d4.png)

**Comment by nileshsheliya** [comment]
This is issue in website_country_restriction module. I have did fixes in it. Now you cal pull latest changes and than test. It working well.

**Comment by vaultllc** [comment]
This is issue in website_country_restriction module. I have did fixes in it. Now you cal pull latest changes and than test. It working well.

**Comment by nikunjantala** [comment]
This is issue in website_country_restriction module. I have did fixes in it. Now you cal pull latest changes and than test. It working well.

**Comment by jans23** [comment]
@DavidNitro please test.

**Comment by DavidNitro** [comment]
Everything works now perfectly fine. Thanks
