### ISSUE TITLE
comply to OCA contribution requirements

### ISSUE THREAD

**Issue by jans23** [Nitrokey/odoo-modules#16]
In order to submit modules to OCA, our modules have to comply to [OCA's contribution requirements](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#tests) first. Attached is a detailed issue list generated by pylint.

[modules_for_oca.txt](https://github.com/Nitrokey/odoo-modules/files/4349342/modules_for_oca.txt)
[nitrokey_modules.txt](https://github.com/Nitrokey/odoo-modules/files/4349340/nitrokey_modules.txt)

Also see pending pull requests:
https://github.com/OCA/sale-workflow/pull/1102
https://github.com/OCA/crm/pull/314
https://github.com/OCA/delivery-carrier/pull/259
https://github.com/OCA/account-payment/pull/324
https://github.com/OCA/e-commerce/pull/342
https://github.com/OCA/l10n-germany/pull/67
https://github.com/OCA/website/pull/706
https://github.com/OCA/account-invoicing/pull/697

**Comment by DavidNitro** [comment]
We want to make all modules for the OCA available. For this purpose, a few adjustments in the code would have to be made which were found by pylint from OCA.
[modules_for_oca.txt](https://github.com/Nitrokey/odoo-modules/files/4348978/modules_for_oca.txt)
