### ISSUE TITLE
abandoned_carts: website sales team not found

### ISSUE THREAD

**Issue by jans23** [Nitrokey/odoo-modules#19]
If a different language than English is used, the query doesn't seem to find the website sales team. This is because of searching for the text string, which is bad practice. Correct should be using website.salesteam_website_sales in in odoo/addons/website_sales/data/data.xml (or in the other file nearby).

**Comment by nileshsheliya** [comment]
I have fixed sales team filter issue.

**Comment by jans23** [comment]
Please fix it for 8.0 too.
-- 
Sent from a mobile device.

**Comment by nikunjantala** [comment]
Issue fixed for Odoo 8.0 too.
