### ISSUE TITLE
abandoned_carts: When clicking on the bin Symbol in "abandoned order", it doesn't remove order

### ISSUE THREAD

**Issue by DavidNitro** [Nitrokey/odoo-modules#7]
When i click on "abandoned order" and then on the bin-button of one order it disappears but when i click on "abandoned order" again the deleted order appears again.

**Comment by nikunjantala** [comment]
bin-button is not remove that record from Odoo. For example, if user click on Abandoned order menu and than system automatically shows all abandoned order. In that if user don't want to remove some records, than they will click on bin-button, so those records are not deleted from Odoo.
