### ISSUE TITLE
Abandoned_Customer should work exactly like the Abandoned_Orders. You should be able to choose how many customers should be deleted at once (maximum 2000).

### ISSUE THREAD

**Issue by DavidNitro** [Nitrokey/odoo-modules#8]

**Comment by nileshsheliya** [comment]
Ok, I will add that configuration for customers too.

**Comment by jans23** [comment]
A single configuration settings is sufficient, but that should be used for both, orders and customers. Please rename accordingly.

**Comment by nileshsheliya** [comment]
Ok.

**Comment by nileshsheliya** [comment]
When executing Abandoned cart cron, do we need to remove customer also or need to remove only Sale Quotations?

**Comment by jans23** [comment]
Remove both please

**Comment by nileshsheliya** [comment]
Ok

**Comment by nileshsheliya** [comment]
Now Abandoned_Customer should works exactly like Abandoned_Orders. Please check it.
